baseURL = "https://taskmasterernest.github.io"
title = "tskmstr"
theme = "smol"
paginate = 5


# Enable Emojis
enableEmoji = true

# Parameters
[params]
    subtitle = "Gone Fishing! - automation: let the robots take over."
    dateFmt = "Jan 2, 2006"
    nuggets = "nuggets"
    description = "The World of tskmstr"
    defaultImage = "https://raw.githubusercontent.com/TaskMasterErnest/smol/master/images/tskmstr.jpg"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/TaskMasterErnest/"
        weight = 1 

    [[menu.footer]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/ernest-woeli-klu/"
        weight = 2 